### ISSUE TITLE
[초기세팅] 프로젝트 세팅

### ISSUE THREAD

**Issue by anonymousRecords** [GCVD-2024/gachon-vd-graduation24-fe#1]
## 💚 어떤 기능인가요?
프로젝트 세팅
## ✅ To Dos
- 프로젝트 생성
- lint 세팅
- global css 세팅
- tanstack-query 세팅
- GSAP 설치

**Comment by anonymousRecords** [comment]
@urjimyu @imeureka 
프로젝트 세팅은 끝났습니다...!
브랜치 파고 했어야 했는데,,, develop에 바로 올려버렸네요,,, (다음부터는 주의하겠습니다,,,🥲)
그래서 여기다가 PR에 적을 내용들 공유해봅니다,,,

## 📌 작업 진행 상황

https://github.com/user-attachments/assets/4da4a1b4-82fa-4791-b955-d1079f919ceb

## 📌 프로젝트 세팅 과정
1. vite를 통해 React 프로젝트 생성
2. Eslint, Prettier 설치 및 설정
3. Styled-Components 설치 및 globalStyles, theme 설정
4. Layout 컴포넌트 구현
5. 라우팅 설정

순으로 진행했습니당

## 📌 폴더 구조
```
src/
|-- components/
|   |--| ThemProvider/
|   |   |-- ThemProvider.tsx
|   |-- Layout/
|   |   |-- Layout.tsx
|   |-- Common/ (공통 컴포넌트들)
|       |-- Button/
|       |-- Input/
|       |-- ...
|-- pages/
|   |-- About/
|   |   |-- components/
|   |   |-- About.tsx
|   |   
|   |-- Work/
|   |   |-- components/
|   |   |-- Work.tsx
|   |   
|   |-- Guest/
|       |-- components/
|       |-- Guest.tsx
|       
|-- routes/
|   |-- Router.tsx
|-- styles/
|   |-- theme.ts
|   |-- globalStyles.ts
|-- constants/
|   |-- constants.ts (상수들)
|-- utils/ (유틸리티 함수들)
|-- hooks/ (커스텀 훅들)
|-- types/ (TypeScript 타입 정의)
|-- App.tsx
|-- main.tsx (entry point)
```

## 📌 설치 내역
- [x] eslint, prettier
- [x] styled-components
- [x] gsap
- [x] react-router-dom
- [x] axios
- [x] tanstack/react-query
- [x] react-helmet-async

**Comment by imeureka** [comment]
확인했습니다! 깔끔하네요 고생많으셨습니다~

**Comment by urjimyu** [comment]
확인했습니다 고생 많으셨어요!! 영상까지 올려주셔서 감사합니다👍
